---
# handlers file for fail2ban
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when:
    - "'fail2ban' in services"
    - ansible_facts.services['fail2ban']['state'] == 'running'
